<?php
/**
 * OrderPostPayload
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Aryeo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aryeo
 *
 * Contact: jarrod@aryeo.com
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aryeo\Model;

use \ArrayAccess;
use \Aryeo\ObjectSerializer;

/**
 * OrderPostPayload Class Doc Comment
 *
 * @category Class
 * @description Payload for creating an order.
 * @package  Aryeo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class OrderPostPayload implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OrderPostPayload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'fulfillment_status' => 'string',
        'internal_notes' => 'string',
        'payment_status' => 'string',
        'address_id' => 'string',
        'customer_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'fulfillment_status' => null,
        'internal_notes' => null,
        'payment_status' => null,
        'address_id' => 'uuid',
        'customer_id' => 'uuid'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fulfillment_status' => 'fulfillment_status',
        'internal_notes' => 'internal_notes',
        'payment_status' => 'payment_status',
        'address_id' => 'address_id',
        'customer_id' => 'customer_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fulfillment_status' => 'setFulfillmentStatus',
        'internal_notes' => 'setInternalNotes',
        'payment_status' => 'setPaymentStatus',
        'address_id' => 'setAddressId',
        'customer_id' => 'setCustomerId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fulfillment_status' => 'getFulfillmentStatus',
        'internal_notes' => 'getInternalNotes',
        'payment_status' => 'getPaymentStatus',
        'address_id' => 'getAddressId',
        'customer_id' => 'getCustomerId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const FULFILLMENT_STATUS_FULFILLED = 'FULFILLED';
    const FULFILLMENT_STATUS_UNFULFILLED = 'UNFULFILLED';
    const PAYMENT_STATUS_PAID = 'PAID';
    const PAYMENT_STATUS_UNPAID = 'UNPAID';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFulfillmentStatusAllowableValues()
    {
        return [
            self::FULFILLMENT_STATUS_FULFILLED,
            self::FULFILLMENT_STATUS_UNFULFILLED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPaymentStatusAllowableValues()
    {
        return [
            self::PAYMENT_STATUS_PAID,
            self::PAYMENT_STATUS_UNPAID,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['fulfillment_status'] = $data['fulfillment_status'] ?? null;
        $this->container['internal_notes'] = $data['internal_notes'] ?? null;
        $this->container['payment_status'] = $data['payment_status'] ?? null;
        $this->container['address_id'] = $data['address_id'] ?? null;
        $this->container['customer_id'] = $data['customer_id'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getFulfillmentStatusAllowableValues();
        if (!is_null($this->container['fulfillment_status']) && !in_array($this->container['fulfillment_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'fulfillment_status', must be one of '%s'",
                $this->container['fulfillment_status'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['fulfillment_status']) && (mb_strlen($this->container['fulfillment_status']) > 255)) {
            $invalidProperties[] = "invalid value for 'fulfillment_status', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['fulfillment_status']) && (mb_strlen($this->container['fulfillment_status']) < 0)) {
            $invalidProperties[] = "invalid value for 'fulfillment_status', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['internal_notes']) && (mb_strlen($this->container['internal_notes']) > 2550)) {
            $invalidProperties[] = "invalid value for 'internal_notes', the character length must be smaller than or equal to 2550.";
        }

        if (!is_null($this->container['internal_notes']) && (mb_strlen($this->container['internal_notes']) < 0)) {
            $invalidProperties[] = "invalid value for 'internal_notes', the character length must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getPaymentStatusAllowableValues();
        if (!is_null($this->container['payment_status']) && !in_array($this->container['payment_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'payment_status', must be one of '%s'",
                $this->container['payment_status'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['payment_status']) && (mb_strlen($this->container['payment_status']) > 255)) {
            $invalidProperties[] = "invalid value for 'payment_status', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['payment_status']) && (mb_strlen($this->container['payment_status']) < 0)) {
            $invalidProperties[] = "invalid value for 'payment_status', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['address_id']) && (mb_strlen($this->container['address_id']) > 36)) {
            $invalidProperties[] = "invalid value for 'address_id', the character length must be smaller than or equal to 36.";
        }

        if (!is_null($this->container['address_id']) && (mb_strlen($this->container['address_id']) < 36)) {
            $invalidProperties[] = "invalid value for 'address_id', the character length must be bigger than or equal to 36.";
        }

        if (!is_null($this->container['customer_id']) && (mb_strlen($this->container['customer_id']) > 36)) {
            $invalidProperties[] = "invalid value for 'customer_id', the character length must be smaller than or equal to 36.";
        }

        if (!is_null($this->container['customer_id']) && (mb_strlen($this->container['customer_id']) < 36)) {
            $invalidProperties[] = "invalid value for 'customer_id', the character length must be bigger than or equal to 36.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fulfillment_status
     *
     * @return string|null
     */
    public function getFulfillmentStatus()
    {
        return $this->container['fulfillment_status'];
    }

    /**
     * Sets fulfillment_status
     *
     * @param string|null $fulfillment_status The fulfillment status of the order. Defaults to \"UNFULFILLED\".
     *
     * @return self
     */
    public function setFulfillmentStatus($fulfillment_status)
    {
        $allowedValues = $this->getFulfillmentStatusAllowableValues();
        if (!is_null($fulfillment_status) && !in_array($fulfillment_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'fulfillment_status', must be one of '%s'",
                    $fulfillment_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        if (!is_null($fulfillment_status) && (mb_strlen($fulfillment_status) > 255)) {
            throw new \InvalidArgumentException('invalid length for $fulfillment_status when calling OrderPostPayload., must be smaller than or equal to 255.');
        }
        if (!is_null($fulfillment_status) && (mb_strlen($fulfillment_status) < 0)) {
            throw new \InvalidArgumentException('invalid length for $fulfillment_status when calling OrderPostPayload., must be bigger than or equal to 0.');
        }

        $this->container['fulfillment_status'] = $fulfillment_status;

        return $this;
    }

    /**
     * Gets internal_notes
     *
     * @return string|null
     */
    public function getInternalNotes()
    {
        return $this->container['internal_notes'];
    }

    /**
     * Sets internal_notes
     *
     * @param string|null $internal_notes Internal notes that will be attached to the order. Viewable only by the team.
     *
     * @return self
     */
    public function setInternalNotes($internal_notes)
    {
        if (!is_null($internal_notes) && (mb_strlen($internal_notes) > 2550)) {
            throw new \InvalidArgumentException('invalid length for $internal_notes when calling OrderPostPayload., must be smaller than or equal to 2550.');
        }
        if (!is_null($internal_notes) && (mb_strlen($internal_notes) < 0)) {
            throw new \InvalidArgumentException('invalid length for $internal_notes when calling OrderPostPayload., must be bigger than or equal to 0.');
        }

        $this->container['internal_notes'] = $internal_notes;

        return $this;
    }

    /**
     * Gets payment_status
     *
     * @return string|null
     */
    public function getPaymentStatus()
    {
        return $this->container['payment_status'];
    }

    /**
     * Sets payment_status
     *
     * @param string|null $payment_status The payment status of the order. Defaults to \"UNPAID\".
     *
     * @return self
     */
    public function setPaymentStatus($payment_status)
    {
        $allowedValues = $this->getPaymentStatusAllowableValues();
        if (!is_null($payment_status) && !in_array($payment_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'payment_status', must be one of '%s'",
                    $payment_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        if (!is_null($payment_status) && (mb_strlen($payment_status) > 255)) {
            throw new \InvalidArgumentException('invalid length for $payment_status when calling OrderPostPayload., must be smaller than or equal to 255.');
        }
        if (!is_null($payment_status) && (mb_strlen($payment_status) < 0)) {
            throw new \InvalidArgumentException('invalid length for $payment_status when calling OrderPostPayload., must be bigger than or equal to 0.');
        }

        $this->container['payment_status'] = $payment_status;

        return $this;
    }

    /**
     * Gets address_id
     *
     * @return string|null
     */
    public function getAddressId()
    {
        return $this->container['address_id'];
    }

    /**
     * Sets address_id
     *
     * @param string|null $address_id ID of the address to associate with the order. UUID Version 4.
     *
     * @return self
     */
    public function setAddressId($address_id)
    {
        if (!is_null($address_id) && (mb_strlen($address_id) > 36)) {
            throw new \InvalidArgumentException('invalid length for $address_id when calling OrderPostPayload., must be smaller than or equal to 36.');
        }
        if (!is_null($address_id) && (mb_strlen($address_id) < 36)) {
            throw new \InvalidArgumentException('invalid length for $address_id when calling OrderPostPayload., must be bigger than or equal to 36.');
        }

        $this->container['address_id'] = $address_id;

        return $this;
    }

    /**
     * Gets customer_id
     *
     * @return string|null
     */
    public function getCustomerId()
    {
        return $this->container['customer_id'];
    }

    /**
     * Sets customer_id
     *
     * @param string|null $customer_id ID of the customer to associate with the order. UUID Version 4.
     *
     * @return self
     */
    public function setCustomerId($customer_id)
    {
        if (!is_null($customer_id) && (mb_strlen($customer_id) > 36)) {
            throw new \InvalidArgumentException('invalid length for $customer_id when calling OrderPostPayload., must be smaller than or equal to 36.');
        }
        if (!is_null($customer_id) && (mb_strlen($customer_id) < 36)) {
            throw new \InvalidArgumentException('invalid length for $customer_id when calling OrderPostPayload., must be bigger than or equal to 36.');
        }

        $this->container['customer_id'] = $customer_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


