<?php
/**
 * TimeslotTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Aryeo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aryeo
 *
 * Contact: jarrod@aryeo.com
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aryeo\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * TimeslotTest Class Doc Comment
 *
 * @category    Class
 * @description A bookable time range, including users that are available.
 * @package     Aryeo
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TimeslotTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Timeslot"
     */
    public function testTimeslot()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "start_at"
     */
    public function testPropertyStartAt()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "end_at"
     */
    public function testPropertyEndAt()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "users"
     */
    public function testPropertyUsers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
