<?php
/**
 * VendorsApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Aryeo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Aryeo
 *
 * Contact: jarrod@aryeo.com
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aryeo\Test\Api;

use \Aryeo\Configuration;
use \Aryeo\ApiException;
use \Aryeo\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * VendorsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aryeo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class VendorsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getVendors
     *
     * Get vendors available to a group..
     *
     */
    public function testGetVendors()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getVendorsId
     *
     * Get vendors available to a group..
     *
     */
    public function testGetVendorsId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
